#################################################
# Application Configuration
#################################################
spring.application.name=url-shortener

#################################################
# Server Configuration
#################################################
server.port=8080

#################################################
# PostgreSQL Database Configuration
#################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/url_shortener
spring.datasource.username=postgres
spring.datasource.password=postgres123

#################################################
# JPA / Hibernate Configuration
#################################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#################################################
# Logging Configuration
#################################################
logging.level.org.springframework=INFO
logging.level.com.avinash.urlshortener=DEBUG
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.avinash.urlshortener.controller
